name: healthcare-accessibility
channels:
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - geopandas
  - shapely
  - pyproj
  - pyogrio
  - pyarrow
  - statsmodels
  - patsy
  - openpyxl
  - rasterio
  - libpysal
  - esda
  - python-docx
  - pytest
